### ISSUE TITLE
Connection lost during ble_sniff

### ISSUE THREAD

**Issue by code-byter** [RCayre/injectable-firmware#7] opened 2022-06-07 20:36 UTC
@RCayre I'm trying to use the mirage `ble_sniff` module with this [nRF52840 MDK USB Dongle](https://www.amazon.de/gp/product/B07MJ12XLG). Unfortunatly I have (different) problems with both, the released pre-built firmware as well as the from source compiled firmware. The first connection is sniffed correctly in both cases, but afterwards problems occur.

### Pre-built firmware
After sniffing the first connection I get the error message `[FAIL] Connection lost !` and mirage exits
![image](https://user-images.githubusercontent.com/10854537/172474373-b0d8dbdd-870f-4b84-a8b7-55803432a936.png)

### Cross-compiled firmware
I compiled the firmware from source with the nRF5 SDK 17.1.0 and flashed it on the dongle. After the connection is sniffed on the device, the second green LED of the dongle turns on (such as when flashing the  firmware), and I get no further output in mirage. When I restart mirage, the interface only works if I unplug the dongle first.
![image](https://user-images.githubusercontent.com/10854537/172474644-0864cf2b-1051-44e1-8a3b-aecf9b6632ab.png)

Are any of these issues already known? Is there a way to debug them and locate the problem?

Merci beaucoup!

**Comment by RCayre** [comment] 2022-06-09 15:53
Hi, thanks for reporting.
No, I was not aware of these issues.

Can you provide me more details about the devices involved in the connection you are trying to sniff ? Does the dongle work with another connection or is it systematic ?

**Comment by code-byter** [comment] 2022-06-09 19:34
@RCayre I tried to sniff the connection of Ray-Ban stories (uses BLE with a GATT server/client).
![image](https://user-images.githubusercontent.com/10854537/172932429-af07d158-c5a7-430e-8be1-59a0878d179f.png)
But I had the same problem with my Logitech MX Master 3, so I assume, it is systematic.

**Comment by code-byter** [comment] 2022-06-23 12:15
Hi @RCayre , do you have any advice how I can further debug this issue?
Thanks a lot!

**Comment by RCayre** [comment] 2022-06-23 14:12
Hi, sorry for the delay !
I'm working on my PhD defense and i'm a bit busy.
I managed to reproduce the issue on my MDK dongle and just pushed a version that seems to fix the bug. Can you give it a try and provide me some feedback ?

**Comment by code-byter** [comment] 2022-06-23 20:57
Hi @RCayre , thanks so much for the fast fix. Yes, the bugfix works, I don't have to remove the dongle anymore between starting mirage, and it keeps working. But when I try to use the ble_sniff module, I keep loosing the connection. I'm not sure if that's a problem with the donge or my mirage installation, so I'll look further into that.

![image](https://user-images.githubusercontent.com/10854537/175398299-0df2b835-33dc-4a18-848c-992c35640ce6.png)

PS: Good luck with your PhD defense!

**Comment by RCayre** [comment] 2022-06-23 21:14
Hi, thanks for the feedback :) 

You should try with another device, because in your last screenshot Mirage don't know how to decode some Control Packets. If they are linked to the connection management, it may explain why the connection breaks: they have probably been added in 5.x version of the specification, which is not supported by Mirage (nor InjectaBLE firmware) yet. If I'm right, as far as I know the only way to sniff a connection involving this device should be Sniffle, which implement a lot of 5.x features.

I would be interested to have a PCAP file with the corresponding traffic, if you can get one.
 
I close this issue temporarily, don't hesitate to re-open it if the problem is not linked to the spec. version.

**Closed as completed by RCayre** 2022-06-23 21:14 UTC
